### ISSUE TITLE
Tabbed Fields Styling Issue

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1769]
# Bug report

When creating a create/update on tabbed fields the styling that should be displayed is not working on fresh install.

![screen shot 2018-12-27 at 12 55 16 am](https://user-images.githubusercontent.com/487798/50473628-842d6500-0972-11e9-846d-cf6bf85504c0.png)

### What I did:

created tabbed fields with 'addField.'

### What I expected to happen:

pretty tabs like before

### What happened:

ugly vertical styling with no background or anything.

### What I've already tried to fix it:

re-install all vendor files, copy/paste crud to fresh install.

### Backpack, Laravel, PHP, DB version:

- almasaeed2010/adminlte        2.4.3
- backpack/base                         1.0.4
- backpack/crud                         3.5.11
- laravel/framework                    5.7.19
- Valet                                          2.0.4

**Comment by fsavina** [comment]
same problem here

**Comment by AbbyJanke** [comment]
For those wanting the older style:

![screen shot 2018-12-29 at 3 15 59 pm](https://user-images.githubusercontent.com/487798/50542867-b6aaae00-0b7c-11e9-8615-24a173ce2f11.png)

I overwrote the /inc/show_tabbed_fields.blade.php file. and added some custom styling.

```css
.tab-container {
  background: #fff;
  border-bottom: 0;
  box-shadow: 0 1px 1px rgba(0,0,0,0.1);
}
.nav-tabs-custom > .nav-tabs > li:first-of-type.active > a {
  border-left-color: #f4f4f4;
}
```
