### ISSUE TITLE
Fixed layout "Export" and "Column visibility" not completely visible

### ISSUE THREAD

**Issue by howest-ward** [Laravel-Backpack/CRUD#1806]
In base.php I set the the skin to 
`'skin' => 'skin-blue fixed',`

The skin changes to the fixed layout from adminlte
But now the dropdown's "Export" and "Column visibility" below the list are not completly visible.

Non-fixed layout:

![scroll-export-not-fixed](https://user-images.githubusercontent.com/37362431/52064405-e2062b80-2574-11e9-93cc-719f402e48a0.gif)

Fixed layout:

![scroll-export-fixed](https://user-images.githubusercontent.com/37362431/52064412-e6324900-2574-11e9-909e-b61fba89c4e2.gif)

**Comment by tabacitu** [comment]
Hi @howest-ward,

True, thank you. I've just pushed a fix to the ```list.css``` file, but since it's already published in your project, consider adding this at the bottom of your ```public/vendor/backpack/crud/css/list.css```:

```css

/*	Allow dropdown buttons to push the height/width of the rapper so that they're entirely visible	*/
	.fixed .wrapper {
		overflow: visible;
	}
```

Cheers!
